name: Compile course
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install -E ghp-compiled
    - name: Compile the course
      run: |
        poetry run python -m naucse_render compile _compiled \
            --edit-repo-url https://github.com/${{ github.repository }} \
            --edit-repo-branch main
    - name: Publish compiled course
      if: github.ref == 'refs/heads/main'
      run: |
        git fetch origin compiled
        poetry run python -m ghp_import -m "Compiled" -b compiled --push _compiled/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: ghp_import
        GIT_COMMITTER_NAME: ghp_import
        EMAIL: none@invalid
    - name: Trigger redeployment
      if: github.ref == 'refs/heads/main'
      run: |
        export REPO_URL=${{ github.server_url }}/${{ github.repository }}
        curl -X POST -H "Accept: application/json" \
          https://hooks.nauc.se/trigger \
          -d '{"repository": "${REPO_URL}", "branch": "compiled"}'
